// <auto-generated />
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Data.Migrations
{
    [DbContext(typeof(ExerciseContext))]
    [Migration("20240525101948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackEnd.Models.Amigo", b =>
                {
                    b.Property<int>("AmigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmigoId"), 1L, 1);

                    b.Property<string>("Amigos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AmigoId");

                    b.ToTable("Amigos");

                    b.HasData(
                        new
                        {
                            AmigoId = 1,
                            Amigos = "andrescabezon@gmail.com",
                            Usuario = "admin@gmail.com"
                        },
                        new
                        {
                            AmigoId = 2,
                            Amigos = "belchite@gmail.com",
                            Usuario = "andrescabezon@gmail.com"
                        },
                        new
                        {
                            AmigoId = 3,
                            Amigos = "nikorx@gmail.com",
                            Usuario = "belchite@gmail.com"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"), 1L, 1);

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intensidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Deporte = "Basket",
                            Descripcion = "En este ejercicios, vamos a necesitar 2 equipos de al menos 3-4 personas cada uno. \nUna vez tengamos listos los equipos, cada uno de los equipos intentará mantener la posesión el mayor tiempo posible.",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "posesion.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3 ,material4",
                            Nombre = "Posesion por equipos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Deporte = "Basket",
                            Descripcion = "A la voz del entrenador todos los jugadores cambiarán de pivotes 4 jugadores siempre quedarán fuera",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0009bas.gif",
                            Intensidad = "Low",
                            Material = "material1, material2",
                            Nombre = "Las 4 esquinas",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Deporte = "Basket",
                            Descripcion = "Se realizan 2 rondos con dos jugadores dentro y el resto fuera pasandose el balón rápidamente \nLos jugadores de fuera llevan en la mano un peto A la señal del entrenador dejan caer el peto al suelo y se dirigen a coger los petos que han dejado los del otro rondo Los dos que no tienen peto juegan dentro del rondo",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "3.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Rondo de pases y velocidad",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 4,
                            Deporte = "Basket",
                            Descripcion = "Cuando el entrenador diga un número saldrá un jugador de cada equipo \nConsiste en coger el balón y conducirlo sin que el otro jugador le quite el balón",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "4.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3",
                            Nombre = "Pañuelito con balón",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 5,
                            Deporte = "Basket",
                            Descripcion = "Pase frontal entre 2 jugadores \nUna vez realizado el pase conducción con bote rápido en dirección al pivote \nEl poseedor del balón intentará llegar antes de que su compañero le coja \nEl jugador que persigue saldrá en el momento en el que su compañero",
                            Dificultad = "Low",
                            Edad = 18,
                            Imagen = "5.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Velocidad",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 6,
                            Deporte = "Basket",
                            Descripcion = "2 equipos juegan a eliminarse \nLos jugadores tendrán el balón entre las manos y no podrán dar más de 3 pasos con él \nSerá eliminado un jugador cuando se le toque con el balón \nEl jugador que salga del campo delimitado también quedará eliminado",
                            Dificultad = "Low",
                            Edad = 18,
                            Imagen = "6.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Caza por equipos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 7,
                            Deporte = "Basket",
                            Descripcion = "Distribución de los jugadores en 2 campos y cada campo de dejará un balón por jugador \nA la señal del entrenador los jugadores de cada equipo intentarán sacar los balones de su campo utilizando para ello tanto las manos,pies,...,mandándolos al campo \ncontrario \nGanará el equipo que en un minuto tenga menos balones en su campo",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "7.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Vaciar el campo",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 8,
                            Deporte = "Basket",
                            Descripcion = "2 equipos formados por 5 jugadores cada uno juega un partido de posesión con las manos \nEl objetivo será conseguir 10 pases seguidos sin ser interceptados \nEl equipo que consiga 10 pases seguidos logrará un punto \nGanará el equipo que consiga mayor número de puntos",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "8.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Los 10 pases",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 9,
                            Deporte = "Basket",
                            Descripcion = "Se delimitará un espacio con un pasillo central de 3 a 5 metros donde se situará un jugador \nEste procurará tocar a los jugadores que intentan pasar de un lado a otro \nSi éstos son tocados se quedarán en el pasillo y agarrados por la mano intentarán tocar al resto de sus compañeros",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "9.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "La muralla",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 10,
                            Deporte = "Basket",
                            Descripcion = "Se divide la frontal de la zona 3 areas diferentes \nEn cada una de ellas el alero recibirá un pase de cada uno de los pasadores (diferentes posiciones) \nEl objetivo será finalizar en canasta el máximo nº de acciones posibles \nLos pases llegan desde diferentes alturas y direcciones por lo que será necesario el desplazamiento y la orientación corporal para finalizar con rapidez y eficacia",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "10.gif",
                            Intensidad = "Low",
                            Material = "material1, material2",
                            Nombre = "Finalizaciones exteriores",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 11,
                            Deporte = "Basket",
                            Descripcion = "4 combinaciones seguidas entre 4 jugadores alternándose las posiciones",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "11.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Rueda de contraataques",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 12,
                            Deporte = "Basket",
                            Descripcion = "Se divide al equipo en 4 grupos que se sitúan en la linea de fondo \nEl primer grupo realiza a velocidad (80%)la distancia de 6,25 a 6,25 m y despúes andando(recuperación) \nLos grupos van saliendo a modo de relevos (llega uno sale el otro)",
                            Dificultad = "Hard",
                            Edad = 7,
                            Imagen = "12.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Farlek a todo el campo",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 13,
                            Deporte = "Basket",
                            Descripcion = "En movimiento alrededor del campo se combinan: Trote, movilidad articular, estiramientos,cambios de dirección y de ritmo",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "13.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Calentamiento general dinámico",
                            Objetivo = "Calentamiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 14,
                            Deporte = "Basket",
                            Descripcion = "Dos atacantes contra 2 defensores con 2 apoyos exteriores situados fuera de la línea de 6,25 \nSi los atacantes consiguen canasta los defensores siguen en su función y éstos cambian su función con los jugadores exteriores \nSi no consiguen canasta se quedan a defender frente al equipo exterior",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "14.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "2 contra 2 con apoyos exteriores",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 15,
                            Deporte = "Basket",
                            Descripcion = "Saque lateral en el que el base parte del poste bajo para salir a recibir al exterior \nEl base se desplaza hacia el lado contrario para realizar un pick and roll con el poste alto (4) \nEl (3) realiza un bloqueo ciego al defensor del (5) y corta la zona hacia el poste alto \nEl (4) tras realizar el pick and roll realiza un bloqueo vertical al defensor del (3) \nSe buscan dos posibles finalizaciones: a)Pase y finalización exterior por parte del (3). b)Pase interior y finalización 1x1 del (5)",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "15.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Bloqueos verticales y ciegos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 16,
                            Deporte = "Basket",
                            Descripcion = "Desplazarse en grupo coordinando el ritmo de movimiento \nUno detrás del ótro agarra la pierna del compañero \nApoyarse uno con el ótro por la espalda",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "16.gif",
                            Intensidad = "Medium",
                            Material = "material1",
                            Nombre = "Fila de cojos",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 17,
                            Deporte = "Basket",
                            Descripcion = "Intentar salir por los huecos que dejen los compañeros entre piernas, brazos o por encima",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "17.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Sal del corro",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 18,
                            Deporte = "Basket",
                            Descripcion = "1)Abdominal superior piernas extendidas \n2)Abdominal inferior elevando alternativamente las piernas extendidas \n3)Oblicuos mediante inclinaciones laterales de tronco \n4)Lumbares con elevación de tronco con el tren inferior apoyado \n5)Abdominal inferior mediante flexión- extensión de piernas simultáneamente a ras de suelo \n6)Abdominal superior con elevación de piernas a 90 º \nRealizar 2 Vueltas completas al circuitoColocarse cogidos de la mano y dentro un jugador",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "18.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Circuito Abdominales 2",
                            Objetivo = "Estiramiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 19,
                            Deporte = "Basket",
                            Descripcion = "1)Lanzar el balón de un brazo a otro por encima de la cabeza \n2)Salto a la comba con pies juntos \n3)Rotación de brazos(uno hacia delante, el otro hacia atrás) \n4ª)Dominios de balón por el aire \n5)Realizar el pino(con o sin apoyo) \n6)Desplazamiento de espaldas en zig-zag \nRealizar 2 Vueltas completas al circuito",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "19.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4, material5",
                            Nombre = "Circuito de coordinación",
                            Objetivo = "Estiramiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 20,
                            Deporte = "Basket",
                            Descripcion = "1)Elevación de pierna al pecho del compañero y buscar con ambas manos puntera y pie apoyado \n2)Apertura lateral de ambas piernas y flexión del tronco hacia delante con ayuda \n3)Ambos compañeros con apertura lateral de ambas piernas y agarrados por las manos tratando de juntar las pelvis \n4)Tumbado boca abajo elevación de una pierna hacia atrás \n5)Tumbado boca abajo elevación de tronco \n6)Tumbado boca arriba llevar ambas piernas hacia el tronco",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "fexi2.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Circuito de flexibilidad por parejas",
                            Objetivo = "Estiramiento",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 21,
                            Deporte = "Basket",
                            Descripcion = "Se enfrentan 2 equipos de 3 jugadores cada uno \nConsiste en mantener la posesión del balón con la ayuda de los dos jugadores que se encuentran fuera del espacio de juego (pivotes) \nEl resto jugarán cada uno en su zona delimitada, que no podrán abandonar",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "20.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Defensa individual cada uno en su zona",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 22,
                            Deporte = "Basket",
                            Descripcion = "Partiendo en caja; (3) y (4) postes bajos, (5) y (1) postes altos El a…",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "21.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Box horizontal y tiro exterior",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 23,
                            Deporte = "Basket",
                            Descripcion = "Elevarse y descender sin ayuda de las manos \nApoyarse uno con el ótro por la espalda",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "22.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "La silla adaptable",
                            Objetivo = "Fisico",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 24,
                            Deporte = "Basket",
                            Descripcion = "1)Apertura lateral de ambas piernas e inclinación del tronco hacia delante buscando las punteras \n2)Fondos de brazos(realizando la lagartija) \n3)Extensión de cuadriceps en equilibrio sobre 1 pierna \n4)De cuclillas estiramiento lateral de una piern \n5)De rodillas inclinación del tronco hacia delante-atrás \n6)Posición del salto de valla buscando las punteras \nRealizar 2 vueltas completas al circuito",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "fexi.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Circuito de Flexibilidad",
                            Objetivo = "Estiramiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 25,
                            Deporte = "Basket",
                            Descripcion = "Consiste en evitar tocar el pivote \nLos jugadores se posicionan en círculo con un pivote en la mitad \nDan vueltas en una dirección y a la señal intentarán traccionar a todos sus compañeros hacia atrás para que uno de éllos toque con cualquier parte del cuerpo el pivote \nEl jugador que lo haya tocado quedará eliminado",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "23.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "¿Quien tocará el pivote?",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 26,
                            Deporte = "Basket",
                            Descripcion = "Los jugadores se colocan formando un círculo \nUn jugador se desplaza a trote por el exterior \nA la voz del entrenador el jugador que se encuentra a su altura debe intentar cogerle antes de que el jugador exterior pueda ocupar su sitio tras dar una vuelta \ncompleta al círculo",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "24.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Te robo la casa",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 27,
                            Deporte = "Basket",
                            Descripcion = "Se colocan en las esquinas del medio del campo \nSe empieza en una línea de fondo \nLos defensores deberán esprintar para llegar a tiempo",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "25.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "Defensa 2x2",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 28,
                            Deporte = "Basket",
                            Descripcion = "Tres jugadores en el centro del campo empezarán atacando \nDos jugadores se colocarán en cada zona como defensores y otros 2 en cada mitad de campo \nAtacan 3 para 2 y van todos al rebote \nEl que coja el rebote pasa rápidamente a uno de los que esperan en las bandas \nEl que cogió el rebote y los 2 jugadores que esperaban se organizan para atacar al otro aro \nLos 4 que se quedan se reparten:2 defienden y 2 esperan en las bandas",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "vuel.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Contrataque de 11",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 29,
                            Deporte = "Basket",
                            Descripcion = " Consiste en llegar lo antes posible a uno de los 4 pivotes \nLos pivotes estarán numerados \nA la señal del entrenador los jugadores se dirigirán al pivote que él haya nombrado \nEl último en llegar quedará elimindo",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "9.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Número y corre",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 30,
                            Deporte = "Basket",
                            Descripcion = "Se juegan situaciones 1 contra 1 en medio campo con el objetivo de llegar a un nº determinado de puntos (7)",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "24.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Puntuación global 1x1",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 32,
                            Deporte = "Futbol",
                            Descripcion = "1)Carrera en sprint realizando slalom 2)Frecuencia apoyo de ambos pies entre pica y pica con aceleración \n3)Carrera en sprint mediante zig- zag \n4)Ampliar la zancada progresivamente 1 apoyo entre pica y pica \n5)Saltos a pies juntos por encima de las vallas y aceleración \n6)Amplitud introduciendo una pierna en cada aro",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0050.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Circuito de Velocidad",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 33,
                            Deporte = "Futbol",
                            Descripcion = "Se divide a la plantilla en 2 equipos que juegan por mantener la posesión del balón \nEn la zona (recuadro) marcado únicamente podrá entrar un jugador por equipo \nSe conseguirá un tanto a favor cuando un equipo sea capaz de realizar una combinación de pase y devolución con uno de sus jugadores que previamente haya entrado en \ndicha zona \nNo se puede permanecer en la zona de marca",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "Glo-0014.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Combinación interior",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 34,
                            Deporte = "Futbol",
                            Descripcion = "Se formará un círculo con todos los jugadores excepto uno que se colocará en el exterior del círculo \nLos jugadores que están situados en círculo se pasan un balón mientrás que el jugador exterior debe de correr hasta interceptarlo \nAl jugador que se le haya interceptado el balón se colocará en el exterior \nUna distancia entre jugador y jugador de 3 metros",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0031.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "Balón viajero",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 35,
                            Deporte = "Futbol",
                            Descripcion = "1)Elevación de brazos por encima de la cabeza con resistencia(hacia abajo) \n2)Fondos de brazos con resistencia \n3)Avanzar haciendo la carretilla \n4)Empujar uno contra otro con brazos extendidos \n5)Pulso en el suelo con apoyo de 1 brazo \n6)Juntar los brazos al cuerpo con resistencia(hacia arriba) \nRealizar 2 vueltas completas al circuito:1ª)30” de acción 30” de recuperación",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "Pfi-0037.gif",
                            Intensidad = "Hard",
                            Material = "material1",
                            Nombre = "Circuito de brazos por parejas",
                            Objetivo = "Estiramiento",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 36,
                            Deporte = "Futbol",
                            Descripcion = "1)Carrera en sprint realizando slalom 2)Frecuencia apoyo de ambos pies entre pica y pica con aceleración \n3)Carrera en sprint mediante zig- zag \n4)Ampliar la zancada progresivamente 1 apoyo entre pica y pica \n5)Saltos a pies juntos por encima de las vallas y aceleración \n6)Amplitud introduciendo una pierna en cada aro",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0050.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Circuito de Velocidad",
                            Objetivo = "Fisico",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 38,
                            Deporte = "Futbol",
                            Descripcion = "El circuito se realizará por repeticiones y se darán 3 vueltas al circuito \n1ª) 20 repeticiones por posta 2ª) 15 repeticiones por posta 3ª) 10 repeticiones por posta \nSe recuperará aproximadamente 30 entre posta y posta \nPostas: 1-Abd.dorsal 2-Lumbares con elevación de piernas 3-Abd.inferior con elevación de piernas 4-Abd. superior piernas extendidas 5-Lumbares con elevación de \ntronco 6-Abd.superior con piernas semiflexionadas",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0029.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Circuito de Abdmominales",
                            Objetivo = "Fisico",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 39,
                            Deporte = "Futbol",
                            Descripcion = "En una zona delimitada por los pivotes se colocarán 5 jugadores,un balón por jugador y 5 pivotes",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0038.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Juego de calentamiento",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 40,
                            Deporte = "Futbol",
                            Descripcion = "1)Flexión y extensión de piernas con oposición \n2)Intentar bajar al suelo frente a la oposición la pierna extendida \n3)Avanzar cargando a burros con el compañero \n4)Saltos por encima del compañero agachado \n5)Flexión-extensión simultánea de las piernas(con oposición),con la espalda apoyada en el suelo \n6)Resistencia a la carrera con agarre por la cintura",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0047.gif",
                            Intensidad = "Medium",
                            Material = "material1",
                            Nombre = "Circuito de piernas por parejas",
                            Objetivo = "Estiramiento",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 41,
                            Deporte = "Futbol",
                            Descripcion = "Se divide el terreno de juego en 3 zonas \ndentro de cada zona se sitúan 2 jugadores ofensivos y 1 jugador defensivo \nEl objetivo será realizar cambios de orientación continuos obligando a que el balón pase por ambas bandas \nCada vez que se consiga un cambio de orientación completo se conseguirá un punto \nLos defensores deben presionar en su zona a los dos jugadores atacantes",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "Esp(centrocamp)-0001",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Cambios de orientación",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 42,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantilla en tres equipos \n2 equipos juegan dentro del campo y el otro equipo se sitúa como apoyo exterior \nLos dos equipos interiores luchan por mantener la posesión del balón para lo que se pueden apoyar en los jugadores que se encuentran en el exterior \nCada 8 o 10 min cambiar el equipo exterior por uno de los interiores",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Glo-0012.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3",
                            Nombre = "Posesión 3 colores",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 43,
                            Deporte = "Futbol",
                            Descripcion = "1)Carrera en sprint hasta la 1ªseñal vuelta recuperando, sprint hasta …",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0035.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "Circuito Fisico- Técnico",
                            Objetivo = "Fisico",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 44,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantilla en 2 equipos \nCada equipo defiende-ataca 3 porterías pequeñas situadas a lo largo de la línea de fondo \nEl gol se conseguirá introduciendo el balón en cualquiera de las 3 porterías",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "Glo-0001.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Partido 6 porterías",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 45,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantilla en equipos de 4 jugadores \nPartido en espacio reducido entre 2 equipos \nCombinar apoyos, paredes, regates,...para meter gol \nEl juego se desarrollará con máxima intensidad",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Glo-0002.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Juego corto 4 contra 4",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 46,
                            Deporte = "Futbol",
                            Descripcion = "Dividir la plantilla en 2 equipos \nJugar 7x7 más 2 porteros \nEstablecer objetivos tácticos según necesidades;pressing, repliegue, cambios de orientación..",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Glo-0010.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Partido medio campo 7x7",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 47,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantila en 2 equipos \nCada equipo mantendrá un jugador en su zona defensiva que no podrá salir de ésta \nPara marcar gol tendrán 2 posibilidades:Tirar sobre la portería defendida por el portero ó conducir a través de los conos",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "Glo-0011.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Juego en 3 zonas",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 48,
                            Deporte = "Futbol",
                            Descripcion = "Se divide a la plantilla en dos equipos \nDentro del campo juegan 4 x 4 ó 5 x 5 (+ 2 porteros), en los fondos y en los laterales de las porterías se colocan jugadores del equipo que ataca \nSe juega en todo momento con la cabeza y únicamente puede cogerse el balón con la mano despues de un bote \nCada 3 o 4 minutos se cambian los jugadores que realizan los apoyos exteriores",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Glo-0005.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Juego corto con la cabeza",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 49,
                            Deporte = "Futbol",
                            Descripcion = "Elevarse y descender sin ayuda de las manos \nApoyarse uno con el ótro por la espalda",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0002.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3, material4",
                            Nombre = "La silla adaptable",
                            Objetivo = "Fisico",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 50,
                            Deporte = "Futbol",
                            Descripcion = "Dos filas con los jugadores colocados espalda contra espalda y con los brazos entrelazados intentan empujar",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "Pfi-0026.gif",
                            Intensidad = "Medium",
                            Material = "material1",
                            Nombre = "La fila que se empuja",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            Descripcion = "El plan Básico que permite a los usuarios visualizar diferentes ejercicios. Además, podrán seguir a otros usuarios y ver sus actividades",
                            Planes = "Basico",
                            Precio = 0,
                            Price = "Gratis"
                        },
                        new
                        {
                            PlanId = 2,
                            Descripcion = "El plan Medium ofrece a los usuarios poder ver TODOS los ejercicios que la aplicación ofrece. Se elimina la publicidad",
                            Planes = "Medium",
                            Precio = 4,
                            Price = "4€"
                        },
                        new
                        {
                            PlanId = 3,
                            Descripcion = "El plan Pro dispone de todas las ventajas del plan Medium, pero añade la funcionalidad de poder comentar y valorar los ejercicios. Además, permite crear ejercicios a los usuarios para aportar más información a la app.",
                            Planes = "Pro",
                            Precio = 7,
                            Price = "7€"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Usage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"), 1L, 1);

                    b.Property<int>("Basico")
                        .HasColumnType("int");

                    b.Property<int>("Basket")
                        .HasColumnType("int");

                    b.Property<int>("Clientes")
                        .HasColumnType("int");

                    b.Property<int>("Futbol")
                        .HasColumnType("int");

                    b.Property<int>("Medium")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pro")
                        .HasColumnType("int");

                    b.HasKey("UsageId");

                    b.ToTable("Usages");

                    b.HasData(
                        new
                        {
                            UsageId = 1,
                            Basico = 30,
                            Basket = 28,
                            Clientes = 50,
                            Futbol = 32,
                            Medium = 15,
                            Month = "January",
                            Pro = 5
                        },
                        new
                        {
                            UsageId = 2,
                            Basico = 25,
                            Basket = 28,
                            Clientes = 50,
                            Futbol = 30,
                            Medium = 20,
                            Month = "February",
                            Pro = 5
                        },
                        new
                        {
                            UsageId = 3,
                            Basico = 30,
                            Basket = 29,
                            Clientes = 55,
                            Futbol = 35,
                            Medium = 18,
                            Month = "March",
                            Pro = 7
                        },
                        new
                        {
                            UsageId = 4,
                            Basico = 33,
                            Basket = 37,
                            Clientes = 65,
                            Futbol = 40,
                            Medium = 25,
                            Month = "April",
                            Pro = 7
                        },
                        new
                        {
                            UsageId = 5,
                            Basico = 40,
                            Basket = 50,
                            Clientes = 70,
                            Futbol = 50,
                            Medium = 20,
                            Month = "May",
                            Pro = 10
                        },
                        new
                        {
                            UsageId = 6,
                            Basico = 50,
                            Basket = 63,
                            Clientes = 90,
                            Futbol = 70,
                            Medium = 25,
                            Month = "June",
                            Pro = 15
                        },
                        new
                        {
                            UsageId = 7,
                            Basico = 65,
                            Basket = 75,
                            Clientes = 105,
                            Futbol = 80,
                            Medium = 27,
                            Month = "July",
                            Pro = 23
                        },
                        new
                        {
                            UsageId = 8,
                            Basico = 70,
                            Basket = 87,
                            Clientes = 120,
                            Futbol = 92,
                            Medium = 20,
                            Month = "August",
                            Pro = 30
                        },
                        new
                        {
                            UsageId = 9,
                            Basico = 50,
                            Basket = 54,
                            Clientes = 75,
                            Futbol = 60,
                            Medium = 15,
                            Month = "September",
                            Pro = 10
                        },
                        new
                        {
                            UsageId = 10,
                            Basico = 50,
                            Basket = 40,
                            Clientes = 70,
                            Futbol = 35,
                            Medium = 10,
                            Month = "October",
                            Pro = 10
                        },
                        new
                        {
                            UsageId = 11,
                            Basico = 45,
                            Basket = 27,
                            Clientes = 65,
                            Futbol = 30,
                            Medium = 10,
                            Month = "November",
                            Pro = 10
                        },
                        new
                        {
                            UsageId = 12,
                            Basico = 45,
                            Basket = 35,
                            Clientes = 60,
                            Futbol = 32,
                            Medium = 5,
                            Month = "Dicember",
                            Pro = 10
                        });
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Apellidos = "admin",
                            Email = "admin@gmail.com",
                            Frase = "admin",
                            Name = "Admin",
                            Password = "admin",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 2,
                            Apellidos = "Torres Berraquero",
                            Email = "andrescabezon@gmail.com",
                            Frase = "Nunca digas nunca!! 😜",
                            Name = "Andrelo",
                            Password = "1234",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 3,
                            Apellidos = "Mearte Tiberio",
                            Email = "gabolon@gmail.com",
                            Frase = "Ahi con las requetonas!!",
                            Name = "Gabolon",
                            Password = "123",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 4,
                            Apellidos = "Ezquerra Belchite",
                            Email = "belchite@gmail.com",
                            Frase = "Soy muy vago!!",
                            Name = "Cristian",
                            Password = "12345",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 5,
                            Apellidos = "Gutierrez Ramon",
                            Email = "nikorx@gmail.com",
                            Frase = "Tomate pero unas vacaciones",
                            Name = "Niko",
                            Password = "33",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 6,
                            Apellidos = "Blancash Sara",
                            Email = "blancash@gmail.com",
                            Frase = "Enamorado de la vida!! 😜",
                            Name = "Cristian",
                            Password = "33",
                            Plan = "Medium"
                        },
                        new
                        {
                            UserId = 7,
                            Apellidos = "Panchez Esteban",
                            Email = "antonion@gmail.com",
                            Frase = "Me gusta quejarme",
                            Name = "Toño",
                            Password = "33",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 8,
                            Apellidos = "Eres Ungenio",
                            Email = "1@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Gabo",
                            Password = "1",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 9,
                            Apellidos = "33",
                            Email = "2@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "3",
                            Password = "2",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 10,
                            Apellidos = "Torres Berraquero",
                            Email = "Atorres@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Andres",
                            Password = "1",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 11,
                            Apellidos = "Torres Berraquero",
                            Email = "Andres@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Andresito",
                            Password = "1",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 12,
                            Apellidos = "prueba prueba",
                            Email = "prueba@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "pruebaFinal",
                            Password = "123",
                            Plan = "Basico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
