// <auto-generated />
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Data.Migrations
{
    [DbContext(typeof(ExerciseContext))]
    [Migration("20240519161605_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackEnd.Models.Amigo", b =>
                {
                    b.Property<int>("AmigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmigoId"), 1L, 1);

                    b.Property<string>("Amigos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AmigoId");

                    b.ToTable("Amigos");

                    b.HasData(
                        new
                        {
                            AmigoId = 1,
                            Amigos = "andrescabezon@gmail.com",
                            Usuario = "admin@gmail.com"
                        },
                        new
                        {
                            AmigoId = 2,
                            Amigos = "belchite@gmail.com",
                            Usuario = "andrescabezon@gmail.com"
                        },
                        new
                        {
                            AmigoId = 3,
                            Amigos = "nikorx@gmail.com",
                            Usuario = "belchite@gmail.com"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"), 1L, 1);

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intensidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Deporte = "Basket",
                            Descripcion = "En este ejercicios, vamos a necesitar 2 equipos de al menos 3-4 person…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "posesion.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3 ,material4",
                            Nombre = "Posesion por equipos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Deporte = "Basket",
                            Descripcion = "A la voz del entrenador todos los jugadores cambiarán de pivotes 4 jug…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0009bas.gif",
                            Intensidad = "Low",
                            Material = "material1, material2",
                            Nombre = "Las 4 esquinas",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Deporte = "Basket",
                            Descripcion = "Se realizan 2 rondos con dos jugadores dentro y el resto fuera pasando…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "3.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Rondo de pases y velocidad",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 4,
                            Deporte = "Basket",
                            Descripcion = "Cuando el entrenador diga un número saldrá un jugador de cada equipo C…",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "4.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3",
                            Nombre = "Pañuelito con balón",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 5,
                            Deporte = "Basket",
                            Descripcion = "Pase frontal entre 2 jugadores Una vez realizado el pase conducción co…",
                            Dificultad = "Low",
                            Edad = 18,
                            Imagen = "5.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Velocidad",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 6,
                            Deporte = "Basket",
                            Descripcion = "2 equipos juegan a eliminarse Los jugadores tendrán el balón entre las…",
                            Dificultad = "Low",
                            Edad = 18,
                            Imagen = "6.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Caza por equipos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 7,
                            Deporte = "Basket",
                            Descripcion = "Distribución de los jugadores en 2 campos y cada campo de dejará un ba…",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "7.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Vaciar el campo",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 8,
                            Deporte = "Basket",
                            Descripcion = "2 equipos formados por 5 jugadores cada uno juega un partido de posesi…",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "8.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Los 10 pases",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 9,
                            Deporte = "Basket",
                            Descripcion = "Se delimitará un espacio con un pasillo central de 3 a 5 metros donde …",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "9.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "La muralla",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 10,
                            Deporte = "Basket",
                            Descripcion = "Se divide la frontal de la zona 3 areas diferentes En cada una de ella…",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "10.gif",
                            Intensidad = "Low",
                            Material = "material1, material2",
                            Nombre = "Finalizaciones exteriores",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 11,
                            Deporte = "Basket",
                            Descripcion = "4 combinaciones seguidas entre 4 jugadores alternándose las posiciones…",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "11.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Rueda de contraataques",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 12,
                            Deporte = "Basket",
                            Descripcion = "Se divide al equipo en 4 grupos que se sitúan en la linea de fondo El …",
                            Dificultad = "Hard",
                            Edad = 7,
                            Imagen = "12.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Farlek a todo el campo",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 13,
                            Deporte = "Basket",
                            Descripcion = "En movimiento alrededor del campo se combinan: Trote, movilidad articu…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "13.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Calentamiento general dinámico",
                            Objetivo = "Calentamiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 14,
                            Deporte = "Basket",
                            Descripcion = "Dos atacantes contra 2 defensores con 2 apoyos exteriores situados fue…",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "14.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "2 contra 2 con apoyos exteriores",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 15,
                            Deporte = "Basket",
                            Descripcion = "Saque lateral en el que el base parte del poste bajo para salir a reci…",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "15.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Bloqueos verticales y ciegos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 16,
                            Deporte = "Basket",
                            Descripcion = "Desplazarse en grupo coordinando el ritmo de movimiento Uno detrás del…",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "16.gif",
                            Intensidad = "Medium",
                            Material = "material1",
                            Nombre = "Fila de cojos",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 17,
                            Deporte = "Basket",
                            Descripcion = "Intentar salir por los huecos que dejen los compañeros entre piernas, …",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "17.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Sal del corro",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 18,
                            Deporte = "Basket",
                            Descripcion = "1)Abdominal superior piernas extendidas 2)Abdominal inferior elevando …",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "18.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Circuito Abdominales 2",
                            Objetivo = "Estiramiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 19,
                            Deporte = "Basket",
                            Descripcion = "1)Lanzar el balón de un brazo a otro por encima de la cabeza 2)Salto a…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "19.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4, material5",
                            Nombre = "Circuito de coordinación",
                            Objetivo = "Estiramiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 20,
                            Deporte = "Basket",
                            Descripcion = "1)Elevación de pierna al pecho del compañero y buscar con ambas manos …",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "fexi2.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Circuito de flexibilidad por parejas",
                            Objetivo = "Estiramiento",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 21,
                            Deporte = "Basket",
                            Descripcion = "Se enfrentan 2 equipos de 3 jugadores cada uno Consiste en mantener la…",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "20.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Defensa individual cada uno en su zona",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 22,
                            Deporte = "Basket",
                            Descripcion = "Partiendo en caja; (3) y (4) postes bajos, (5) y (1) postes altos El a…",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "21.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Box horizontal y tiro exterior",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 23,
                            Deporte = "Basket",
                            Descripcion = "Elevarse y descender sin ayuda de las manos Apoyarse uno con el ótro p…",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "22.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "La silla adaptable",
                            Objetivo = "Fisico",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 24,
                            Deporte = "Basket",
                            Descripcion = "1)Apertura lateral de ambas piernas e inclinación del tronco hacia del…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "fexi.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Circuito de Flexibilidad",
                            Objetivo = "Estiramiento",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 25,
                            Deporte = "Basket",
                            Descripcion = "Consiste en evitar tocar el pivote Los jugadores se posicionan en círc…",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "23.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "¿Quien tocará el pivote?",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 26,
                            Deporte = "Basket",
                            Descripcion = "Los jugadores se colocan formando un círculo Un jugador se desplaza a …",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "24.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Te robo la casa",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 27,
                            Deporte = "Basket",
                            Descripcion = "Se colocan en las esquinas del medio del campo Se empieza en una línea…",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "25.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "Defensa 2x2",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 28,
                            Deporte = "Basket",
                            Descripcion = "Tres jugadores en el centro del campo empezarán atacando Dos jugadores…",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "vuel.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Contrataque de 11",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 29,
                            Deporte = "Basket",
                            Descripcion = "Consiste en llegar lo antes posible a uno de los 4 pivotes Los pivotes…",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "9.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Número y corre",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 30,
                            Deporte = "Basket",
                            Descripcion = "Se juegan situaciones 1 contra 1 en medio campo con el bojetivo de lle…",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "24.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Puntuación global 1x1",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 32,
                            Deporte = "Futbol",
                            Descripcion = "1)Carrera en sprint realizando slalom 2)Frecuencia apoyo de ambos pies…",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0050.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Circuito de Velocidad",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 33,
                            Deporte = "Futbol",
                            Descripcion = "Se divide a la plantilla en 2 equipos que juegan por mantener la poses…",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "Glo-0014.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Combinación interior",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 34,
                            Deporte = "Futbol",
                            Descripcion = "Se formará un círculo con todos los jugadores excepto uno que se coloc…",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0031.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "Balón viajero",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 35,
                            Deporte = "Futbol",
                            Descripcion = "1)Elevación de brazos por encima de la cabeza con resistencia(hacia ab…",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "Pfi-0037.gif",
                            Intensidad = "Hard",
                            Material = "material1",
                            Nombre = "Circuito de brazos por parejas",
                            Objetivo = "Estiramiento",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 36,
                            Deporte = "Futbol",
                            Descripcion = "1)Carrera en sprint realizando slalom 2)Frecuencia apoyo de ambos pies…",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0050.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Circuito de Velocidad",
                            Objetivo = "Fisico",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 38,
                            Deporte = "Futbol",
                            Descripcion = "El circuito se realizará por repeticiones y se darán 3 vueltas al circ…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0029.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Circuito de Abdmominales",
                            Objetivo = "Fisico",
                            Personas = "Individual"
                        },
                        new
                        {
                            ExerciseId = 39,
                            Deporte = "Futbol",
                            Descripcion = "En una zona delimitada por los pivotes se colocarán 5 jugadores,un bal…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0038.gif",
                            Intensidad = "Low",
                            Material = "material1",
                            Nombre = "Juego de calentamiento",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 40,
                            Deporte = "Futbol",
                            Descripcion = "1)Flexión y extensión de piernas con oposición 2)Intentar bajar al sue…",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0047.gif",
                            Intensidad = "Medium",
                            Material = "material1",
                            Nombre = "Circuito de piernas por parejas",
                            Objetivo = "Estiramiento",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 41,
                            Deporte = "Futbol",
                            Descripcion = "Se divide el terreno de juego en 3 zonas dentro de cada zona se sitúan…",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "Esp(centrocamp)-0001",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Cambios de orientación",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 42,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantilla en tres equipos 2 equipos juegan dentro del cam…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Glo-0012.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3",
                            Nombre = "Posesión 3 colores",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 43,
                            Deporte = "Futbol",
                            Descripcion = "1)Carrera en sprint hasta la 1ªseñal vuelta recuperando, sprint hasta …",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Pfi-0035.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2",
                            Nombre = "Circuito Fisico- Técnico",
                            Objetivo = "Fisico",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 44,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantilla en 2 equipos Cada equipo defiende-ataca 3 porte…",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "Glo-0001.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Partido 6 porterías",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 45,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantilla en equipos de 4 jugadores Partido en espacio re…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Glo-0002.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Juego corto 4 contra 4",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 46,
                            Deporte = "Futbol",
                            Descripcion = "Dividir la plantilla en 2 equipos Jugar 7x7 más 2 porteros Establecer …",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Glo-0010.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Partido medio campo 7x7",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 47,
                            Deporte = "Futbol",
                            Descripcion = "Dividir a la plantila en 2 equipos Cada equipo mantendrá un jugador en…",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "Glo-0011.gif",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Juego en 3 zonas",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 48,
                            Deporte = "Futbol",
                            Descripcion = "Se divide a la plantilla en dos equipos Dentro del campo juegan 4 x 4 …",
                            Dificultad = "Medium",
                            Edad = 14,
                            Imagen = "Glo-0005.gif",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3, material4",
                            Nombre = "Juego corto con la cabeza",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 49,
                            Deporte = "Futbol",
                            Descripcion = "Elevarse y descender sin ayuda de las manos Apoyarse uno con el otro p…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "Pfi-0002.gif",
                            Intensidad = "Low",
                            Material = "material1, material2, material3, material4",
                            Nombre = "La silla adaptable",
                            Objetivo = "Fisico",
                            Personas = "Parejas"
                        },
                        new
                        {
                            ExerciseId = 50,
                            Deporte = "Futbol",
                            Descripcion = "Dos filas con los jugadores colocados espalda contra espalda y con los…",
                            Dificultad = "Medium",
                            Edad = 7,
                            Imagen = "Pfi-0026.gif",
                            Intensidad = "Medium",
                            Material = "material1",
                            Nombre = "La fila que se empuja",
                            Objetivo = "Fisico",
                            Personas = "Grupos"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            Descripcion = "El plan Básico que permite a los usuarios visualizar diferentes ejercicios. Además, podrán seguir a otros usuarios y ver sus actividades",
                            Planes = "Basico",
                            Precio = 0,
                            Price = "Gratis"
                        },
                        new
                        {
                            PlanId = 2,
                            Descripcion = "El plan Medium ofrece a los usuarios poder ver TODOS los ejercicios que la aplicación ofrece. Se elimina la publicidad",
                            Planes = "Medium",
                            Precio = 4,
                            Price = "4€"
                        },
                        new
                        {
                            PlanId = 3,
                            Descripcion = "El plan Pro dispone de todas las ventajas del plan Medium, pero añade la funcionalidad de poder comentar y valorar los ejercicios. Además, permite crear ejercicios a los usuarios para aportar más información a la app.",
                            Planes = "Pro",
                            Precio = 7,
                            Price = "7€"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Apellidos = "admin",
                            Email = "admin@gmail.com",
                            Frase = "admin",
                            Name = "Admin",
                            Password = "admin",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 2,
                            Apellidos = "Torres Berraquero",
                            Email = "andrescabezon@gmail.com",
                            Frase = "Nunca digas nunca!! 😜",
                            Name = "Andrelo",
                            Password = "1234",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 3,
                            Apellidos = "Mearte Tiberio",
                            Email = "gabolon@gmail.com",
                            Frase = "Ahi con las requetonas!!",
                            Name = "Gabolon",
                            Password = "123",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 4,
                            Apellidos = "Ezquerra Belchite",
                            Email = "belchite@gmail.com",
                            Frase = "Soy muy vago!!",
                            Name = "Cristian",
                            Password = "12345",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 5,
                            Apellidos = "Gutierrez Ramon",
                            Email = "nikorx@gmail.com",
                            Frase = "Tomate pero unas vacaciones",
                            Name = "Niko",
                            Password = "33",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 6,
                            Apellidos = "Blancash Sara",
                            Email = "blancash@gmail.com",
                            Frase = "Enamorado de la vida!! 😜",
                            Name = "Cristian",
                            Password = "33",
                            Plan = "Medium"
                        },
                        new
                        {
                            UserId = 7,
                            Apellidos = "Panchez Esteban",
                            Email = "antonion@gmail.com",
                            Frase = "Me gusta quejarme",
                            Name = "Toño",
                            Password = "33",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 8,
                            Apellidos = "Eres Ungenio",
                            Email = "1@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Gabo",
                            Password = "1",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 9,
                            Apellidos = "33",
                            Email = "2@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "3",
                            Password = "2",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 10,
                            Apellidos = "Torres Berraquero",
                            Email = "Atorres@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Andres",
                            Password = "1",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 11,
                            Apellidos = "Torres Berraquero",
                            Email = "Andres@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Andresito",
                            Password = "1",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 12,
                            Apellidos = "prueba prueba",
                            Email = "prueba@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "pruebaFinal",
                            Password = "123",
                            Plan = "Basico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
