// <auto-generated />
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Data.Migrations
{
    [DbContext(typeof(ExerciseContext))]
    partial class ExerciseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackEnd.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"), 1L, 1);

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intensidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Deporte = "Basket",
                            Descripcion = "En este ejercicios, vamos a necesitar 2 equipos de al menos 3-4 person…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3 ,material4",
                            Nombre = "Posesion por equipos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Deporte = "Basket",
                            Descripcion = "A la voz del entrenador todos los jugadores cambiarán de pivotes 4 jug…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Low",
                            Material = "material1, material2",
                            Nombre = "Las 4 esquinas",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Deporte = "Basket",
                            Descripcion = "Se realizan 2 rondos con dos jugadores dentro y el resto fuera pasando…",
                            Dificultad = "Low",
                            Edad = 7,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Rondo de pases y velocidad",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 4,
                            Deporte = "Basket",
                            Descripcion = "Cuando el entrenador diga un número saldrá un jugador de cada equipo C…",
                            Dificultad = "Low",
                            Edad = 14,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Low",
                            Material = "material1, material2, material3",
                            Nombre = "Pañuelito con balón",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 5,
                            Deporte = "Basket",
                            Descripcion = "Pase frontal entre 2 jugadores Una vez realizado el pase conducción co…",
                            Dificultad = "Low",
                            Edad = 18,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Velocidad",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 6,
                            Deporte = "Basket",
                            Descripcion = "2 equipos juegan a eliminarse Los jugadores tendrán el balón entre las…",
                            Dificultad = "Low",
                            Edad = 18,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Hard",
                            Material = "material1, material2, material3",
                            Nombre = "Caza por equipos",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 7,
                            Deporte = "Basket",
                            Descripcion = "Distribución de los jugadores en 2 campos y cada campo de dejará un ba…",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Vaciar el campo",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 8,
                            Deporte = "Basket",
                            Descripcion = "2 equipos formados por 5 jugadores cada uno juega un partido de posesi…",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "Los 10 pases",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 9,
                            Deporte = "Basket",
                            Descripcion = "Se delimitará un espacio con un pasillo central de 3 a 5 metros donde …",
                            Dificultad = "Medium",
                            Edad = 18,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Medium",
                            Material = "material1, material2, material3",
                            Nombre = "La muralla",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 10,
                            Deporte = "Basket",
                            Descripcion = "Se divide la frontal de la zona 3 areas diferentes En cada una de ella…",
                            Dificultad = "Hard",
                            Edad = 18,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Low",
                            Material = "material1, material2",
                            Nombre = "Finalizaciones exteriores",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 11,
                            Deporte = "Basket",
                            Descripcion = "4 combinaciones seguidas entre 4 jugadores alternándose las posiciones…",
                            Dificultad = "Hard",
                            Edad = 14,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Rueda de contraataques",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        },
                        new
                        {
                            ExerciseId = 12,
                            Deporte = "Basket",
                            Descripcion = "Se divide al equipo en 4 grupos que se sitúan en la linea de fondo El …",
                            Dificultad = "Hard",
                            Edad = 7,
                            Imagen = "http://entrenamientosdebaloncesto.es/Ejercicios/Baloncesto_Castellano/…",
                            Intensidad = "Hard",
                            Material = "material1, material2",
                            Nombre = "Farlek a todo el campo",
                            Objetivo = "Calentamiento",
                            Personas = "Grupos"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            Descripcion = "El plan Básico que permite a los usuarios visualizar diferentes ejercicios. Además, podrán seguir a otros usuarios y ver sus actividades",
                            Planes = "Basico",
                            Precio = 0,
                            Price = "Gratis"
                        },
                        new
                        {
                            PlanId = 2,
                            Descripcion = "El plan Medium ofrece a los usuarios poder ver TODOS los ejercicios que la aplicación ofrece. Se elimina la publicidad",
                            Planes = "Medium",
                            Precio = 4,
                            Price = "4€"
                        },
                        new
                        {
                            PlanId = 3,
                            Descripcion = "El plan Pro dispone de todas las ventajas del plan Medium, pero añade la funcionalidad de poder comentar y valorar los ejercicios. Además, permite crear ejercicios a los usuarios para aportar más información a la app.",
                            Planes = "Pro",
                            Precio = 7,
                            Price = "7€"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Apellidos = "admin",
                            Email = "admin@gmail.com",
                            Frase = "admin",
                            Name = "Admin",
                            Password = "admin",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 2,
                            Apellidos = "Torres Berraquero",
                            Email = "andrescabezon@gmail.com",
                            Frase = "Nunca digas nunca!! 😜",
                            Name = "Andrelo",
                            Password = "1234",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 3,
                            Apellidos = "Mearte Tiberio",
                            Email = "gabolon@gmail.com",
                            Frase = "Ahi con las requetonas!!",
                            Name = "Gabolon",
                            Password = "123",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 4,
                            Apellidos = "Ezquerra Belchite",
                            Email = "belchite@gmail.com",
                            Frase = "Soy muy vago!!",
                            Name = "Cristian",
                            Password = "12345",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 5,
                            Apellidos = "Gutierrez Ramon",
                            Email = "nikorx@gmail.com",
                            Frase = "Tomate pero unas vacaciones",
                            Name = "Niko",
                            Password = "33",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 6,
                            Apellidos = "Blancash Sara",
                            Email = "blancash@gmail.com",
                            Frase = "Enamorado de la vida!! 😜",
                            Name = "Cristian",
                            Password = "33",
                            Plan = "Medium"
                        },
                        new
                        {
                            UserId = 7,
                            Apellidos = "Panchez Esteban",
                            Email = "antonion@gmail.com",
                            Frase = "Me gusta quejarme",
                            Name = "Toño",
                            Password = "33",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 8,
                            Apellidos = "Eres Ungenio",
                            Email = "1@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Gabo",
                            Password = "1",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 9,
                            Apellidos = "33",
                            Email = "2@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "3",
                            Password = "2",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 10,
                            Apellidos = "Torres Berraquero",
                            Email = "Atorres@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Andres",
                            Password = "1",
                            Plan = "Basico"
                        },
                        new
                        {
                            UserId = 11,
                            Apellidos = "Torres Berraquero",
                            Email = "Andres@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "Andresito",
                            Password = "1",
                            Plan = "Pro"
                        },
                        new
                        {
                            UserId = 12,
                            Apellidos = "prueba prueba",
                            Email = "prueba@gmail.com",
                            Frase = "Hey there! I'm using Pro-Tactic",
                            Name = "pruebaFinal",
                            Password = "123",
                            Plan = "Basico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
